In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [7]:
myarr = np.array(mylist)

In [8]:
myarr

array([1, 2, 3])

In [9]:
type(myarr)

numpy.ndarray

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
len(np.linspace(0,10,11))

11

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.random.rand(1,3)

array([[0.25431957, 0.59557144, 0.69285392]])

In [34]:
np.random.randn(10)

array([ 0.07527045, -1.1954651 , -0.87809242, -0.83479454, -0.37984194,
        0.38603239,  0.22902071,  0.32942662,  0.34747172,  0.41835389])

In [35]:
np.random.randn(2,3)

array([[-0.91726431,  0.85765296, -0.8619719 ],
       [ 0.66976749, -0.09993676, -1.08526557]])

In [40]:
np.random.randint(0,101,(4,5))

array([[12, 80, 56, 62, 25],
       [20, 21, 46, 92, 25],
       [73,  0, 46, 72, 45],
       [42,  9, 21, 81, 17]])

In [41]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [44]:
arr = np.arange(0,25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0,101,10)

In [50]:
ranarr.max()

95

In [51]:
ranarr.min()

10

In [52]:
ranarr.argmax()

8

In [53]:
ranarr.argmin()

6

In [54]:
ranarr.dtype

dtype('int32')

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.shape

(25,)

In [59]:
arr = arr.reshape(5,5)

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.shape

(5, 5)

In [64]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])